os:
 - linux

dist: trusty

env:
 - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

addons:
  chrome: beta

language: node_js

node_js:
 - "8.1.3"

script:
 - npm run puppeteer
 - npm run build
 - npm run timestamp
 - npm run sample

before_install:
 - chmod +x build/deploy.sh

after_success:
 - ./build/deploy.sh

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: out
  email: "mht-deploy@travis-ci.org"
  on:
    branch: master

branches:
  only:
  - master

git:
  depth: 3
